const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');

const articleDir = '/Users/quyue/www/blog/2026-05-05-cycloid-trochoid-math';

const CARDS = [
  {
    slug: 'brachistochrone',
    eyebrow: 'THE PROBLEM THAT STARTED IT ALL',
    title: 'The Curve That Took 5 Centuries to Master',
    dek: "Johann Bernoulli posed a challenge: find the curve of fastest descent. The answer wasn't a straight line \u2014 it was a cycloid.",
    quote: "Newton, Leibniz, and Bernoulli raced to solve it. The cycloid won.",
    bullets: ['Brachistochrone = "shortest time" in Greek', 'Steep initial slope accelerates particles faster', 'Beats straight lines even when endpoints aren\'t vertical'],
    theme: 'forest'
  },
  {
    slug: 'three-curves',
    eyebrow: 'ONE PARAMETER, THREE WORLDS',
    title: 'Cycloid, Curtate, Prolate',
    dek: "Move the tracing point inside or outside the rolling circle. The same equation generates three fundamentally different curves.",
    quote: "Three completely different-looking curves, generated by one equation with one changed parameter.",
    bullets: ['Cycloid (d=r): cusps where circle touches ground', 'Curtate (d<r): wavy, never touches ground', 'Prolate (d>r): loops that cross over themselves'],
    theme: 'ocean'
  },
  {
    slug: 'real-world',
    eyebrow: 'WHERE CYCLOIDS HIDDEN IN PLAIN SIGHT',
    title: 'Gear Teeth, Spirograph, Roller Coasters',
    dek: "The cycloid's smooth rolling contact makes it ideal for mechanical gears. Spirograph toys generate trochoids. Railway transitions follow cycloidal curves.",
    quote: "The cycloid isn't just a mathematical curiosity \u2014 engineers have been exploiting its properties for centuries.",
    bullets: ['Mechanical gears: smooth velocity transfer', 'Roller coasters: constant curvature transition', 'Spirograph: mechanical trochoid generator'],
    theme: 'ember'
  }
];

const THEMES = {
  forest: { accent: '#00FF94', bg: '#001A0D', muted: '#00CC77' },
  ocean:  { accent: '#00B4D8', bg: '#000D1A', muted: '#0090B8' },
  ember:  { accent: '#FF6B35', bg: '#0D0D0D', muted: '#CC5529' }
};

(async () => {
  const browser = await chromium.launch();
  for (let i = 0; i < CARDS.length; i++) {
    const card = CARDS[i];
    const t = THEMES[card.theme];
    const bulletsHtml = card.bullets.map(function(b) {
      return '<li class="text-[#999999] text-[16px] leading-snug">' + b + '</li>';
    }).join('');
    var html = '<!DOCTYPE html>\n' +
'<html lang="en">\n' +
'<head>\n' +
'<meta charset="UTF-8">\n' +
'<meta name="viewport" content="width=device-width, initial-scale=1.0">\n' +
'<script src="https://cdn.tailwindcss.com"></script>\n' +
'<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700;800;900&display=swap" rel="stylesheet">\n' +
'<style>body { font-family: \'Outfit\', sans-serif; }</style>\n' +
'</head>\n' +
'<body class="bg-[' + t.bg + '] min-h-screen flex items-center justify-center">\n' +
'  <div class="w-[1080px] px-[80px] py-20">\n' +
'    <p class="text-[' + t.accent + '] text-[13px] tracking-[0.25em] uppercase font-semibold mb-6">' + card.eyebrow + '</p>\n' +
'    <h2 class="text-white text-[56px] font-black leading-tight mb-6">' + card.title + '</h2>\n' +
'    <p class="text-[#AAAAAA] text-[22px] leading-relaxed mb-10 max-w-[800px]">' + card.dek + '</p>\n' +
'    <blockquote class="border-l-4 border-[' + t.accent + '] pl-6 mb-10">\n' +
'      <p class="text-[#DDDDDD] text-[22px] italic leading-relaxed">"' + card.quote + '"</p>\n' +
'    </blockquote>\n' +
'    <ul class="space-y-2">' + bulletsHtml + '</ul>\n' +
'  </div>\n' +
'</body>\n' +
'</html>';

    var page = await browser.newPage({ viewport: { width: 1080, height: 900 } });
    await page.setContent(html, { waitUntil: 'networkidle' });
    await page.screenshot({ path: path.join(articleDir, 'card-' + String(i+1).padStart(2,'0') + '.png'), fullPage: true });
    await page.close();
    console.log('Card ' + (i+1) + ' saved: ' + card.slug);
  }
  await browser.close();
  console.log('All cards done');
})();
